# Here we are telling bazel, build this cpp files and call it as CPPLIB
cc_library(
    name = "sample",
    srcs = ["sample.cpp"],
    hdrs = ["sample.hpp"],
    visibility = ["//visibility:public"],
)

